services:
  db:
    image: postgres:15-alpine
    container_name: solaris-monitoring_db
    restart: always
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin_password
      POSTGRES_DB: edsia_db
    ports:
      - "5433:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  api:
    build: .
    container_name: solaris-monitoring_api
    restart: always
    ports:
      - "8000:8000"
    depends_on:
      - db
    environment:
      - DATABASE_URL=postgresql://admin:admin_password@db:5432/edsia_db
      - UPDATE_DATE=${UPDATE_DATE:-No definida}
    volumes:
      - ./src:/app/src

volumes:
  postgres_data: