"""initial schema

Revision ID: 2ef74455ca98
Revises: 
Create Date: 2026-09-12 00:09:27.381522

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision: str = '2ef74455ca98'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('photovoltaic_cells',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('location', sa.String(length=200), nullable=False),
    sa.Column('rated_voltage', sa.Float(), nullable=False),
    sa.Column('max_safe_voltage', sa.Float(), nullable=False),
    sa.Column('efficiency_threshold', sa.Float(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('photovoltaic_cells', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_photovoltaic_cells_name'), ['name'], unique=True)

    op.create_table('readings',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('cell_id', sa.Integer(), nullable=False),
    sa.Column('voltage_measured', sa.Float(), nullable=False),
    sa.Column('efficiency_percentage', sa.Float(), nullable=False),
    sa.Column('is_anomaly', sa.Boolean(), nullable=False),
    sa.Column('timestamp', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['cell_id'], ['photovoltaic_cells.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('readings', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_readings_cell_id'), ['cell_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_readings_timestamp'), ['timestamp'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('readings', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_readings_timestamp'))
        batch_op.drop_index(batch_op.f('ix_readings_cell_id'))

    op.drop_table('readings')
    with op.batch_alter_table('photovoltaic_cells', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_photovoltaic_cells_name'))

    op.drop_table('photovoltaic_cells')
    # ### end Alembic commands ###
